apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-jvm-deployment
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-jvm-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-jvm-deployment
    spec:
      containers:
      - image: polinchw/demo:dev-11
        imagePullPolicy: Always
        name: demo
        resources: 
          limits:
            cpu: 250m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 512Mi
            
