apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-jvm-deployment
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-jvm-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-jvm-deployment
    spec:
      containers:
      - image: polinchw/demo:1.0.0
        imagePullPolicy: Always
        name: demo
        resources: 
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 150Mi
            
