apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-grallvm-deployment
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-grallvm-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-grallvm-deployment
    spec:
      containers:
      - image: polinchw/demo:2.0.0
        name: demo
        resources: 
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 50Mi
            
