apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-grallvm-service
  name: demo-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-grallvm-deployment