apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-deployment
  name: demo-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-deployment